//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class MyHandClosedMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/MyHandClosed";
        public override string RosMessageName => k_RosMessageName;

        public bool hand_is_closed;

        public MyHandClosedMsg()
        {
            this.hand_is_closed = false;
        }

        public MyHandClosedMsg(bool hand_is_closed)
        {
            this.hand_is_closed = hand_is_closed;
        }

        public static MyHandClosedMsg Deserialize(MessageDeserializer deserializer) => new MyHandClosedMsg(deserializer);

        private MyHandClosedMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.hand_is_closed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.hand_is_closed);
        }

        public override string ToString()
        {
            return "MyHandClosedMsg: " +
            "\nhand_is_closed: " + hand_is_closed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
