//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class MyPosRotMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/MyPosRot";
        public override string RosMessageName => k_RosMessageName;

        public float pos_x;
        public float pos_y;
        public float pos_z;
        public float roll;
        public float pitch;
        public float yaw;

        public MyPosRotMsg()
        {
            this.pos_x = 0.0f;
            this.pos_y = 0.0f;
            this.pos_z = 0.0f;
            this.roll = 0.0f;
            this.pitch = 0.0f;
            this.yaw = 0.0f;
        }

        public MyPosRotMsg(float pos_x, float pos_y, float pos_z, float roll, float pitch, float yaw)
        {
            this.pos_x = pos_x;
            this.pos_y = pos_y;
            this.pos_z = pos_z;
            this.roll = roll;
            this.pitch = pitch;
            this.yaw = yaw;
        }

        public static MyPosRotMsg Deserialize(MessageDeserializer deserializer) => new MyPosRotMsg(deserializer);

        private MyPosRotMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos_x);
            deserializer.Read(out this.pos_y);
            deserializer.Read(out this.pos_z);
            deserializer.Read(out this.roll);
            deserializer.Read(out this.pitch);
            deserializer.Read(out this.yaw);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos_x);
            serializer.Write(this.pos_y);
            serializer.Write(this.pos_z);
            serializer.Write(this.roll);
            serializer.Write(this.pitch);
            serializer.Write(this.yaw);
        }

        public override string ToString()
        {
            return "MyPosRotMsg: " +
            "\npos_x: " + pos_x.ToString() +
            "\npos_y: " + pos_y.ToString() +
            "\npos_z: " + pos_z.ToString() +
            "\nroll: " + roll.ToString() +
            "\npitch: " + pitch.ToString() +
            "\nyaw: " + yaw.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
